config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :mailing_list_emails, only: [:create]

  resources :users, only: [:new, :create]

  namespace :admin do
    get "/dashboard", to: "users#show"
    resources :properties, only: [:index, :show, :update]
    resources :reservations, only: [:index, :show]
    resources :users, only: [:index, :update]
  end

  namespace :user, path: ":user_name", as: :user do
    resources :properties, only: [:create, :index, :update, :show]
    resources :reservations, only: [:new, :create, :index]
  end

  resources :properties, only: [:new, :index]

  get ":user_name/dashboard", to: "users#show", as: :user_dashboard

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :property
  has_many :reservation_nights
  #validates_uniqueness_of :property_id, scope: [:checkin, :checkout]

  def self.reserved?(checkin, checkout)
    dates = date_range(checkin, checkout)
    all.map do |reservation|
      reservation.check_if_reserved(dates)
    end.flatten.include?(true)
  end

  def self.total_revenue
    sum(:order_total)
  end

  def self.daily_average_revenue
    return if Reservation.count == 0
    total_revenue / group_by_day(:checkin).count.length
  end

  def self.weekly_average_revenue
    return if Reservation.count == 0
    total_revenue / group_by_week(:checkin).count.length
  end


  def check_if_reserved(dates)
    reservation_nights.map do |night|
      dates.include?(night.night)
    end
  end

  def self.date_range(checkin, checkout)
    (checkin.to_s.to_date..checkout.to_s.to_date).to_a
  end
  
  def self.by_date
    order(checkin: :asc)
  end

  def self.reservation_index(status)
    if status == "current"
      where("checkin >= ?", Time.zone.now.beginning_of_day).by_date
    elsif status == "past"
      where("checkin < ?", Time.zone.now.beginning_of_day).by_date
    end
  end

  def process_stripe_payment
    customer = Stripe::Customer.create email: email,
                                       card: card_token
    Stripe::Charge.create customer: customer.id,
                          amount: order_total,
                          description: id,
                          currency: 'usd'
  end

  def formatted_total
    "$#{order_total}"
  end
end

app/controllers/admin/reservations_controller.rb
class Admin::ReservationsController < ApplicationController
  def index
    @reservations = Reservation.reservation_index(params[:status])
  end

  def show
    @reservation = Reservation.find(params[:id])
  end
end

app/controllers/user/reservations_controller.rb
class User::ReservationsController < ApplicationController
  def create
    res_processor = ReservationProcessor.new(current_user, reservation_params)
    @reservation = res_processor.reservation
    if @reservation.save
      @reservation.process_stripe_payment
      OrderMailer.order_email(@reservation).deliver_now
      flash[:info] = "Thanks for your order! :)"
      session[:cart] = nil
      redirect_to user_dashboard_path(current_user.slug)
    else
      flash.now[:alert] = "Sorry, friend.  Something went wrong :(... Please try again."
      render :new
    end
  end

  def index
    @reservations = current_user.reservations
  end

  private

    def reservation_params
      params.permit(:stripeEmail, :stripeToken, :stripeShippingName, :stripeShippingAddressLine1, :stripeShippingAddressCity, :stripeShippingAddressZip, :stripeShippingAddressState, :stripeShippingAddressZip, :property_user_id, :property_id, :checkin, :checkout, :reservation_total)
    end

end

app/helpers/reservations_helper.rb
module ReservationsHelper
  def reservation_status
    params[:status]
  end

  def display_checkin_date(reservation)
    "Check-in: #{reservation.checkin.strftime("%B %-d, %Y")}"
  end

  def display_checkout_date(reservation)
    "Checkout: #{reservation.checkout.strftime("%B %-d, %Y")}"
  end
end

app/helpers/user/reservations_helper.rb
module User::ReservationsHelper
end

app/views/admin/reservations/index.html.erb
<h1 class="<%= reservation_status %> admin-reservations-index-header"><%= reservation_status %> reservations</h1><br>
<div class="table-responsive">
  <table class="table table-hover table-condensed table-bordered table-striped">
    <thead>
      <tr>
        <th>reservation date</th>
        <th>reservation id</th>
        <th>property owner</th>
        <th>customer name</th>
        <th>total price</th>
      </tr>
    </thead>
    <% @reservations.each do |reservation| %>
      <tr id="<%= reservation.id %>-reservation">
        <td class="text-nowrap">
           <%= display_checkin_date(reservation) %>
           <br>
           <%= display_checkout_date(reservation) %>
        </td>
        <td>
          <%= link_to reservation.id, admin_reservation_path(reservation.id) %>
        </td>
        <td class="text-nowrap">
            <%= reservation.property.user.fullname %>
        </td>
        <td>
          <%= reservation.fullname %>
        </td>
        <td>
          <%= "$#{reservation.order_total}" %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/reservations/show.html.erb
<div>
  <h2 id="reservation-title">RESERVATION INFO</h2>
</div>

<div class="container">
  <div class="reservation-info">
    <div class="col-md-8">
      Reservation ID: <%= @reservation.id %>
    </div>
    <div class="col-md-4">
      <%= display_checkin_date(@reservation) %>
    </div>
    <div class="col-md-8">
      Property ID: <%= link_to @reservation.property.id, admin_property_path(@reservation.property.id) %>
    </div>
    <div class="col-md-4">
      <%= display_checkout_date(@reservation) %>
    </div>
    <hr>
    <div class="col-lg-12">
      Property Owner: <%=@reservation.property.user.fullname  %>
    </div>
    <div class="col-lg-12">
      Customer Name: <%=@reservation.fullname %>
    </div>
    <hr>
    <div class="col-lg-8">
    </div>
    <div class="col-lg-4" id="formatting-total">
      Total Price
    </div>
    <hr>
    <div class="col-lg-8">
    </div>
    <div class="col-lg-4">
      <%= @reservation.formatted_total %>
    </div>
  </div>
</div>