config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :mailing_list_emails, only: [:create]

  resources :users, only: [:new, :create]

  namespace :admin do
    get "/dashboard", to: "users#show"
    resources :properties, only: [:index, :show, :update]
    resources :reservations, only: [:index, :show]
    resources :users, only: [:index, :update]
  end

  namespace :user, path: ":user_name", as: :user do
    resources :properties, only: [:create, :index, :update, :show]
    resources :reservations, only: [:new, :create, :index]
  end

  resources :properties, only: [:new, :index]

  get ":user_name/dashboard", to: "users#show", as: :user_dashboard

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/views/shared/_admin_nav.html.erb
<nav role="navigation" class="navbar navbar-default custom-navbar navbar-fixed-top">
  <div class="nav-container">
    <%= render partial: "shared/navbar_brand" %>
    <div class="navbar-nav pull-right">
      <ul class="nav pull-left user-cart">
        <li class="dropdown pull-right nav-icon">
          <a href="#" data-toggle="dropdown" style="color:#777; margin-top: 5px;" class="dropdown-toggle">
            <i class="fa fa-user fa-lg"></i>
          </a>
          <ul class="dropdown-menu">
            <li class="name-in-dropdown">
                <%= current_user.fullname.downcase %>
            </li>
            <li>
              <%= link_to "logout", logout_path, method: :delete %>
            </li>
          </ul>
        </li>
        <li class="pull-right nav-icon">
          <a id="menu-toggle" href="#menu-toggle" style="color:#777; margin-top: 5px;", class"admin-menu-toggle">
            <i class="fa fa-compass fa-lg"></i>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_city_imgs.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-4 category-landing">
      <div class="text-center category-unit miami-landing">
        <h1><%= link_to "Miami", {:controller => "properties", :action => "index", :location => "Miami, FL", :radius => "1000" } %></h1>
      </div>
    </a>
    </div>
    <div class="col-sm-4 category-landing">
      <div class="text-center category-unit los-angeles-landing">
        <h1><%= link_to "Los Angeles", {:controller => "properties", :action => "index", :location => "Los Angeles, CA", :radius => "1000" } %></h1>
      </div>
    </a>
    </div>
    <div class="col-sm-4 category-landing">
      <div class="text-center category-unit new-york-landing category-unit-gifts" id='new-york'>
        <h1><%= link_to "New York", {:controller => "properties", :action => "index", :location => "New York, NY", :radius => "1000" } %></h1>
      </div>
    </a>
    </div>
  </div>
</div>

app/views/shared/_current_user.html.erb
<ul class="nav pull-left user-cart">

  <% if current_user %>
  <%= link_to "List my Pad", new_property_path, method: :get, class:"btn btn-little-owl btn-lg list-my-pad" %>
    <li class="dropdown pull-right nav-icon">
      <a href="#" data-toggle="dropdown" style="color:#777; margin-top: 5px;" class="dropdown-toggle"><i class="fa fa-user fa-lg"></i></a>
      <ul class="dropdown-menu">
        <li class="name-in-dropdown">
          <%= current_user.fullname.downcase %>
        </li>
        <li><%= link_to "my dashboard", user_dashboard_path(current_user) %></li>
        <li>
          <%= link_to "logout", logout_path, method: :delete %>
        </li>
      </ul>
    </li>
  <% else %>
    <li class="pull-right nav-icon">
      <a id="login" href="/login" style="color:#777; margin-top: 5px;"><i class="fa fa-sign-in fa-lg"></i></a>
    </li>
  <% end %>
</ul>

app/views/shared/_mailing_list.html.erb
<div class="row">
  <div class="col-xs-12 text-center mailing-list">
    <span class="glyphicon glyphicon-envelope mail-icon" aria-hidden="true"></span>
    <h2>Be in the know.</h2>
    <p>Sign up for tips, deals, and wisdom.</p>
    <br>
    <%= form_tag mailing_list_emails_path do %>
      <%= email_field_tag :email, params[:email], placeholder: "email", class: "update-form"%><br><br>
      <%= submit_tag "sign up", class:"btn btn-little-owl btn-sm"  %>
    <% end %>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav role="navigation" class="navbar navbar-default custom-navbar">
  <div class="nav-container">
    <%= render partial: "shared/navbar_brand" %>
      <div class="navbar-nav pull-right">
        <%= render partial: "shared/current_user" %>
      </div>
  </div>
</nav>

app/views/shared/_navbar_brand.html.erb
<div class="navbar-header pull-left">
    <a class="logo-link" href="/"><%= image_tag("nav-logo.png", id:"nav-logo_img", class:"logo-img") %>
    <span class="little co-name">C.A.</span><span class="owl co-name">M.P</span></a><br>
</div>

app/views/shared/_no_listings.html.erb
<div class="container">
  <div class="col-sm-6 col-sm-offset-2">
    <br>
    <h4>You don't have any listings</h4><br>

    <h5>Make money by renting out your extra space on CAMP. You’ll also get to meet interesting travelers from around the world!</h5>

    <%= link_to "Post a new Listing", new_property_path, method: :get, class:"btn btn-little-owl btn-md" %>
  </div>
</div>

app/views/shared/_no_trips.html.erb
<div class="container">
  <div class="col-sm-6 col-sm-offset-2">
    <br>
    <h4>You don't have any trips</h4><br>

    <h5>You deserve a vacation! Check out some cool properties and start crashing!</h5>

    <%= link_to "Find a pad!", properties_path, method: :get, class:"btn btn-little-owl btn-md list-my-pad" %>
  </div>
</div>

app/views/shared/_options.html.erb
<% [*1..10].each do |n| %>
  <option><%= n %></option>
<% end %>

app/views/shared/_search_map.html.erb
<div id="map">
  <script>
     function initMap() {

       var properties = <%= @properties_geo_info %>
       var location = {lat: <%= @geocoded_location["lat"] %>, lng: <%= @geocoded_location["lng"] %> }

       var mapDiv = document.getElementById('map');


       var map = new google.maps.Map(mapDiv, {
         center: location,
         zoom: 7,
         animation: google.maps.Animation.DROP
       });

       for (i = 0; i < properties.length; i++) {
          var new_location = {lat: properties[i][0], lng: properties[i][1] };

          var image = 'https://cdn3.iconfinder.com/data/icons/mapicons/icons/tent.png';
          let make_marker = new google.maps.Marker({
             position: new_location,
             map: map,
             animation: google.maps.Animation.DROP,
             icon: image
           });

         let infowindow = new google.maps.InfoWindow({
           content: "something here"
            });
          make_marker.addListener('click', function() {
            infowindow.open(map, make_marker);
          });
        }


        var marker = new google.maps.Marker({
          position: location,
          label: "X",
          map: map,
        });
     }
  </script>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAl_jt_OiEmR9tIZeJ3MYhuCvxVQn7u-O4&callback=initMap&region=US" async defer></script>
</div>

app/views/shared/_searchbar_properties.html.erb
  <div class="filter-search" id: "searchbar">
    <form role="form" action='/properties' method="get">
      <input name="utf8" type="hidden" value="&#x2713;" />
      <div class="col-sm-3">
        <div class="form-group" id="location" >
          <label class="sr-only" for="location">Location</label>
          <input type="text" name="destination" class="form-control" id="location" value="<%= params[:destination] %>" placeholder="Enter City, State" required=>
        </div>
      </div>
      <div class="col-sm-2">
        <div class="form-group">
          <label class="sr-only" for="checkin">Check in</label>
          <div class="input-group">
            <input type="text" class="form-control" name="checkin" id="checkin" value="<%= session[:checkin] %>" placeholder="<%= set_checkin_placeholder %>" required>
            <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
          </div>
        </div>
      </div>
      <div class="col-sm-2">
        <div class="form-group">
          <label class="sr-only" for="checkout">Check out</label>
          <div class="input-group">
            <input type="text" class="form-control" name="checkout" id="checkout" value="<%= session[:checkout] %>" placeholder="<%= set_checkout_placeholder %>" required>
            <span class="input-group-addon" style="padding-right: 8px"><i class="glyphicon glyphicon-calendar"></i></span>
          </div>
        </div>
      </div>
      <div class="col-sm-2">
        <div class="form-group">
          <label class="sr-only" for="guest">Guest</label>
          <select id="guests" name="guest" class="form-control" placeholder="Select Guests" required>
            <option default selected><% if session[:guests] %><%= session[:guests] %><% else %> 3 Guests <% end %> </option>
              <option value="1 Guest">1 Guest</option>
              <option value="2 Guests">2 Guests</option>
              <option value="3 Guests">3 Guests</option>
              <option value="4 Guests">4 Guests</option>
              <option value="5 Guests">5 Guests</option>
              <option value="6 Guests">6 Guests</option>
              <option value="7 Guests">7 Guests</option>
              <option value="8 Guests">8 Guests</option>
              <option value="9 Guests">9 Guests</option>
              <option value="10 Guests">10 Guests</option>
              <option value="11 Guests">11 Guests</option>
              <option value="12 Guests">12 Guests</option>
              <option value="13 Guests">13 Guests</option>
              <option value="14 Guests">14 Guests</option>
              <option value="15 Guests">15 Guests</option>
              <option value="16 Guests">16+ Guests</option>
          </select>
        </div>
      </div>
      <div class="col-sm-2">
      <div class="form-group">
        <%= number_field_tag "radius", value=session[:radius], class:"form-control form-control-success pull-left" %>
      </div>
    </div>
      <div class="col-sm-1">
        <button type="submit" class="btn btn-primary">Search</button>
      </div>
    </form>
  </div>

app/views/shared/_sidebar_nav.html.erb
<ul class="sidebar-nav">
  <li class="sidebar-brand">
    <a href="#">
    Hey <%= current_user.first_name.downcase %>
    </a>
  </li>
  <li>
    <%= link_to "dashboard", admin_dashboard_path %>
  </li>
  <li>
    <%= link_to "pending properties", admin_properties_path(status: "pending") %>
  </li>
  <li>
    <%= link_to "active properties", admin_properties_path(status: "active") %>
  </li>
  <li>
    <%= link_to "inactive properties", admin_properties_path(status: "inactive") %>
  </li>
  <li>
    <%= link_to "current reservations", admin_reservations_path(status: "current") %>
  </li>
  <li>
    <%= link_to "past reservations", admin_reservations_path(status: "past") %>
  </li>
  <li>
    <%= link_to "active users", admin_users_path(status: "active")%>
  </li>
  <li>
    <%= link_to "inactive users", admin_users_path(status: "inactive") %>
  </li>
</ul>

app/views/shared/_user_dashboard_header.html.erb
<div class="order-hero-unit">
  <div class="container text-center hero-container">
    <h1></h1>
  </div>
</div>
<div class="row dashboard-navbar">
  <div class="col-sm-6 col-sm-offset-2">
    <ul class="nav navbar-nav">
      <li><%= link_to "My Dashboard", user_dashboard_path(current_user.slug), class:"dashboard-navbar-menu-item" %></li>
      <li><%= link_to "My Listings", user_properties_path(current_user.slug), class:"dashboard-navbar-menu-item" %></li>
      <li><%= link_to "My Trips", user_reservations_path(current_user.slug), class:"dashboard-navbar-menu-item" %></li>
    </ul>
  </div>
</div>

app/views/shared/_visitor_header.html.erb
<div class="order-hero-unit">
  <div class="container text-center hero-container">
    <h1></h1>
  </div>
</div>
<div class="row dashboard-navbar">
  <div class="col-sm-6 col-sm-offset-2">
    <ul class="nav navbar-nav">
  </div>
</div>