config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :mailing_list_emails, only: [:create]

  resources :users, only: [:new, :create]

  namespace :admin do
    get "/dashboard", to: "users#show"
    resources :properties, only: [:index, :show, :update]
    resources :reservations, only: [:index, :show]
    resources :users, only: [:index, :update]
  end

  namespace :user, path: ":user_name", as: :user do
    resources :properties, only: [:create, :index, :update, :show]
    resources :reservations, only: [:new, :create, :index]
  end

  resources :properties, only: [:new, :index]

  get ":user_name/dashboard", to: "users#show", as: :user_dashboard

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  before_save :build_name
  before_create :create_slug
  has_many :reservations
  has_many :properties

  validates :fullname, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  enum role: %w(default platform_admin)

  def build_name
    self.first_name = fullname.split[0]
    self.last_name = fullname.split[1..-1].join(" ")
  end

  def create_slug
    self.slug = fullname.parameterize
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users = User.where(status: params[:status]).order(:id)
  end

  def update
    @user = User.find(params[:id])

    @user.update(user_params)
    flash[:info] = "User ID: #{@user.id} has been updated."
    redirect_to admin_users_path(status: @user.status)
  end

  def show
    @reservations = Reservation.all
  end

  private
  def user_params
    params.require(:user).permit(:status)
  end
end

app/controllers/user/properties_controller.rb
class User::PropertiesController < ApplicationController
  def create
    @property = current_user.properties.create(property_params)
    PropertyAmenitizer.new(amenity_params, @property)
    ImageCreator.create_images(image_params, @property)
    if @property.save
      flash[:info] = "Congrats #{current_user.fullname}! Your new listing is pending approval."
      redirect_to user_dashboard_path(current_user.slug)
    else
      flash[:alert] = "Sorry! #{@property.errors.full_messages.join(',')}"
      redirect_to new_property_path(current_user.slug)
    end
  end

  def index
    @properties = current_user.properties
    @amenities = Amenity.all
  end

  def update
    @property = current_user.properties.find(params[:id])
    PropertyAmenitizer.update(params[:property][:amenity_ids], @property)
    ImageCreator.create_images(image_params, @property)
    if @property.update(property_params)
      flash[:info] = "You have updated your listing."
      redirect_to user_properties_path(current_user.slug)
    else
      flash[:alert] = "Sorry! #{@property.errors.full_messages.join(',')}"
      redirect_to user_properties_path(current_user.slug)
    end
  end

  def show
    if params[:checkin] && params[:checkout]
      session[:checkin] = params[:checkin]
      session[:checkout] = params[:checkout]
    end

    @property = Property.find(params[:id])
  end

private
  def property_params
    params.require(:property).permit(:title, :description, :street, :unit, :city, :state, :zip, :price, :bedrooms, :bathrooms, :sleeps, :property_type_id, :amenity_ids)
  end

  def image_params
    params[:property][:images]
  end

  def amenity_params
    params[:property][:amenities]
  end
end

app/controllers/user/reservations_controller.rb
class User::ReservationsController < ApplicationController
  def create
    res_processor = ReservationProcessor.new(current_user, reservation_params)
    @reservation = res_processor.reservation
    if @reservation.save
      @reservation.process_stripe_payment
      OrderMailer.order_email(@reservation).deliver_now
      flash[:info] = "Thanks for your order! :)"
      session[:cart] = nil
      redirect_to user_dashboard_path(current_user.slug)
    else
      flash.now[:alert] = "Sorry, friend.  Something went wrong :(... Please try again."
      render :new
    end
  end

  def index
    @reservations = current_user.reservations
  end

  private

    def reservation_params
      params.permit(:stripeEmail, :stripeToken, :stripeShippingName, :stripeShippingAddressLine1, :stripeShippingAddressCity, :stripeShippingAddressZip, :stripeShippingAddressState, :stripeShippingAddressZip, :property_user_id, :property_id, :checkin, :checkout, :reservation_total)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def new_checkout
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:info] = "Hey #{@user.fullname}, welcome to C.A.M.P."
      redirect_to root_path
    else
      flash.now[:alert] = "Sorry, friend.  Something went wrong :(... Please try again."
      render :new
    end
  end

  def show
    @user = current_user
  end

private

  def user_params
    params.require(:user).permit(:fullname, :email, :password)
  end
end

app/helpers/user/properties_helper.rb
module User::PropertiesHelper
  def us_states
    [ ['Select State','Select State'],
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end
end

app/helpers/user/reservations_helper.rb
module User::ReservationsHelper
end

app/views/admin/users/index.html.erb
<h1 class="<%= users_status %> admin-users-index-header"><%= users_status %> users</h1>
<br>
<div class="table-responsive">
  <table class="table table-hover table-condensed table-bordered table-striped">
    <thead>
      <tr>
        <th>user id</th>
        <th>name</th>
        <th>total properties</th>
        <th>status</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <% @users.each do |user| %>
      <tr id="<%= user.id %>-user">
        <td class="text-nowrap">
          <%= user.id %>
        </td>
        <td>
          <%=  user.fullname %>
        </td>
        <td class="text-nowrap">
          <%= user.properties.count %>
        </td>
        <td>
          <%= user.status  %>
        </td>
        <%= form_for [:admin, user], url: admin_user_path(user.id) do |f| %>
        <td><%= f.select(:status, options_for_select(%w(active inactive), user.status), {prompt: user.status }) %></td>
          <td><%= f.submit "update user", class:"btn btn-checkout btn-s"%></td>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 text-center dashboard-rev-header" id="total-display-date">
      <span class="number-header">$<%= number_with_delimiter(@reservations.total_revenue, delimiter: ',')%></span><span class="text-header"> total revenue</span>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 text-center dashboard-rev-header" id="checkin-per-month">
      <h2>check-in's per month</h2>
  </div>
  <hr>
  <div class="row">
    <div class="col-xs-12 text-center">
      <%= line_chart Reservation.group_by_month(:checkin).count %>
    </div>
  </div>
  <div class="row rev-data-row text-center" id="platform-diagnostics">
    <div class="col-xs-1 text-center">
    </div>
    <div class="col-xs-2 rev-data text-center">
      <h4 class="data-point-header"><small>daily avg</small></h4>
      <p class="revenue-span">$<%= number_with_delimiter(@reservations.daily_average_revenue, delimiter: ',')%></p>
    </div>
    <div class="col-xs-3 rev-data text-center">
      <h4 class="data-point-header"><small>weekly avg</small></h4>
      <span class="revenue-span">$<%= number_with_delimiter(@reservations.weekly_average_revenue, delimiter: ',')%></span>
    </div>
    <div class="col-xs-2 rev-data text-center">
      <h4 class="data-point-header"><small>orders</small></h4>
      <span class="revenue-span"><%= Reservation.count %></span>
    </div>
    <div class="col-xs-2 rev-data text-center">
      <h4 class="data-point-header"><small>users</small></h4>
      <span class="revenue-span"><%= User.count %></span>
    </div>
    <div class="col-xs-2 text-center">
    </div>
  </div>
  <hr>
  <div class="row dashboard-second-row">
    <div class="col-xs-12 text-center dashboard-rev-sub-header">
      <span class="text-header">United States</span>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-6">
      <%= geo_chart Reservation.group(:state).count, library: {region: 'US', resolution: 'provinces'} %>
    </div>
    <div class="col-xs-6">
      <%= pie_chart Reservation.group(:city).count %>
    </div>
  </div>
</div>