config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :mailing_list_emails, only: [:create]

  resources :users, only: [:new, :create]

  namespace :admin do
    get "/dashboard", to: "users#show"
    resources :properties, only: [:index, :show, :update]
    resources :reservations, only: [:index, :show]
    resources :users, only: [:index, :update]
  end

  namespace :user, path: ":user_name", as: :user do
    resources :properties, only: [:create, :index, :update, :show]
    resources :reservations, only: [:new, :create, :index]
  end

  resources :properties, only: [:new, :index]

  get ":user_name/dashboard", to: "users#show", as: :user_dashboard

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :user
  belongs_to :property_type
  has_many :images
  has_many :reservations
  has_many :reservation_nights, through: :reservations
  has_many :property_amenities
  has_many :amenities, through: :property_amenities
  accepts_nested_attributes_for :amenities

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :street, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :bedrooms, presence: true
  validates :bathrooms, presence: true
  validates :sleeps, presence: true

  geocoded_by :full_address
  after_validation :geocode

  def self.search(search)
   properties = find_by_city_state_sleeps(parse_search(search))
   search_by_dates(properties)
  end

  def self.find_by_city_state_sleeps(search)
    Property.where(status: "active").order(price: :desc).near("#{@city}, #{@state}, US", @radius).where('sleeps >= ?', @guest).limit(50)
  end

  def self.city_search(params)
    Property.where(status: "active").order(price: :desc).near("#{params[:location]}, US", params[:radius]).where('sleeps >= ?', 3).limit(50)
  end

  def self.default
    Property.where(status: "active").order(price: :desc).near("Denver, CO, US", 3000).where('sleeps >= ?', 3).limit(50)
  end

  def self.by_date
    order(updated_at: :desc)
  end

  def self.search_by_name(search)
    search = search.strip
    user = User.find_by('first_name || last_name || fullname ILIKE ?', "%#{search}%").id
    where(user_id: user)
  end

  def owner
    user = User.find(self.user_id)
    user.fullname
  end

  def display_total
    "$#{self.price}"
  end

  def date
    updated_at.strftime("%B %-d, %Y")
  end

  def self.search_by_dates(properties)
    properties.map do |property|
      property unless property.reservations.reserved?(@checkin, @checkout)
    end.compact
  end

  def self.parse_search(search)
    @city = search[:destination].split(',')[0]
    @state = search[:destination].split(',')[-1].strip
    @guest = search[:guest].split[0]
    @checkin = search[:checkin].delete('-').to_i
    @checkout = search[:checkout].delete('-').to_i
    @radius = search[:radius].to_i
  end

  def nights_reserved
    reservation_nights.map do |res_night|
      res_night.night
    end
  end

  def full_address
    "#{zip}"
  end

  def possible_nights(checkin, checkout)
    (checkin.to_date..checkout.to_date).count
  end

  def cost(checkin, checkout)
    possible_nights(checkin, checkout) * price
  end
end

app/models/property_type.rb
class PropertyType < ActiveRecord::Base
  has_many :properties

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  before_save :build_name
  before_create :create_slug
  has_many :reservations
  has_many :properties

  validates :fullname, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  enum role: %w(default platform_admin)

  def build_name
    self.first_name = fullname.split[0]
    self.last_name = fullname.split[1..-1].join(" ")
  end

  def create_slug
    self.slug = fullname.parameterize
  end
end

app/controllers/admin/properties_controller.rb
class Admin::PropertiesController < ApplicationController

  def index
    @properties = Property.by_date
    @properties = Property.where(status: params[:status]).by_date.limit(50)
  end

  def update
    @property = Property.find(params[:id])

    @property.update(property_params)
    flash[:info] = "Property ID: #{@property.id} from Owner #{@property.owner} has been updated."
    redirect_to admin_properties_path(status: @property.status)
  end

  def show
    @property = Property.find(params[:id])
  end

  private
  def property_params
    params.require(:property).permit(:status)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users = User.where(status: params[:status]).order(:id)
  end

  def update
    @user = User.find(params[:id])

    @user.update(user_params)
    flash[:info] = "User ID: #{@user.id} has been updated."
    redirect_to admin_users_path(status: @user.status)
  end

  def show
    @reservations = Reservation.all
  end

  private
  def user_params
    params.require(:user).permit(:status)
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  include PropertiesHelper

  def new
    @property = Property.new
    @amenities = Amenity.all
    guest_user?
  end

  def index
    set_sessions
    if params[:destination]
      @properties = Property.search(params)
      location = find_location(params)
      @properties_geo_info = set_geo_info(@properties)
      @geocoded_location = set_geo_location(location)
    elsif params[:location]
      @properties = Property.city_search(params)
      location = find_location(params)
      @properties_geo_info = set_geo_info(@properties)
      @geocoded_location = set_geo_location(location)
    else
      @properties = Property.default
      @properties_geo_info = set_geo_info(@properties)
      @geocoded_location = {"lat"=>39.7392358, "lng"=>-104.990251}
    end
  end

  private
    def property_params
      params.require(:property).permit(:title, :description, :street, :unit, :city, :state, :zip, :price, :bedrooms, :bathrooms, :sleeps, :property_type_id)
    end

    def image_params
      params[:property][:image]
    end

    def amenity_params
      params[:property][:amenities]
    end
end

app/controllers/user/properties_controller.rb
class User::PropertiesController < ApplicationController
  def create
    @property = current_user.properties.create(property_params)
    PropertyAmenitizer.new(amenity_params, @property)
    ImageCreator.create_images(image_params, @property)
    if @property.save
      flash[:info] = "Congrats #{current_user.fullname}! Your new listing is pending approval."
      redirect_to user_dashboard_path(current_user.slug)
    else
      flash[:alert] = "Sorry! #{@property.errors.full_messages.join(',')}"
      redirect_to new_property_path(current_user.slug)
    end
  end

  def index
    @properties = current_user.properties
    @amenities = Amenity.all
  end

  def update
    @property = current_user.properties.find(params[:id])
    PropertyAmenitizer.update(params[:property][:amenity_ids], @property)
    ImageCreator.create_images(image_params, @property)
    if @property.update(property_params)
      flash[:info] = "You have updated your listing."
      redirect_to user_properties_path(current_user.slug)
    else
      flash[:alert] = "Sorry! #{@property.errors.full_messages.join(',')}"
      redirect_to user_properties_path(current_user.slug)
    end
  end

  def show
    if params[:checkin] && params[:checkout]
      session[:checkin] = params[:checkin]
      session[:checkout] = params[:checkout]
    end

    @property = Property.find(params[:id])
  end

private
  def property_params
    params.require(:property).permit(:title, :description, :street, :unit, :city, :state, :zip, :price, :bedrooms, :bathrooms, :sleeps, :property_type_id, :amenity_ids)
  end

  def image_params
    params[:property][:images]
  end

  def amenity_params
    params[:property][:amenities]
  end
end

app/controllers/user/reservations_controller.rb
class User::ReservationsController < ApplicationController
  def create
    res_processor = ReservationProcessor.new(current_user, reservation_params)
    @reservation = res_processor.reservation
    if @reservation.save
      @reservation.process_stripe_payment
      OrderMailer.order_email(@reservation).deliver_now
      flash[:info] = "Thanks for your order! :)"
      session[:cart] = nil
      redirect_to user_dashboard_path(current_user.slug)
    else
      flash.now[:alert] = "Sorry, friend.  Something went wrong :(... Please try again."
      render :new
    end
  end

  def index
    @reservations = current_user.reservations
  end

  private

    def reservation_params
      params.permit(:stripeEmail, :stripeToken, :stripeShippingName, :stripeShippingAddressLine1, :stripeShippingAddressCity, :stripeShippingAddressZip, :stripeShippingAddressState, :stripeShippingAddressZip, :property_user_id, :property_id, :checkin, :checkout, :reservation_total)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def new_checkout
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:info] = "Hey #{@user.fullname}, welcome to C.A.M.P."
      redirect_to root_path
    else
      flash.now[:alert] = "Sorry, friend.  Something went wrong :(... Please try again."
      render :new
    end
  end

  def show
    @user = current_user
  end

private

  def user_params
    params.require(:user).permit(:fullname, :email, :password)
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
  def guest_user?
    if current_user.nil?
      session[:referrer] = new_property_path
      redirect_to login_path
    end
  end

  def set_sessions
    session[:checkin] = params[:checkin]
    session[:checkout] = params[:checkout]
    session[:guests] = params[:guest]
    session[:radius] = params[:radius]
  end

  def property_status
    params[:status]
  end

  def find_location(params)
    if params[:destination]
      params[:destination]
    else
      params[:location]
    end
  end

  def set_geo_info(properties)
    GeoProcessor.new(properties).geo_info
  end

  def set_geo_location(location)
    Geocoder.search(location).first.data["geometry"]["location"]
  end

  def find_city(params)
    params[:location].split(',')[0]
  end

  def set_checkin_placeholder
    if session[:checkin]
      session[:checkin]
    else
      "checkin"
    end
  end

  def set_checkout_placeholder
    if session[:checkout]
      session[:checkout]
    else
      "checkout"
    end
  end

  def set_guests_placeholder
    if session[:guest]
      session[:guest]
    else
      "Guests"
    end
  end

  def min_price(properties)
    if properties.empty?
      100
    else
      properties.min_by do |property|
        property.price
      end.price
    end
  end

  def max_price(properties)
    if properties.empty?
      1000
    else
      properties.max_by do |property|
        property.price
      end.price
    end
  end
end

app/helpers/user/properties_helper.rb
module User::PropertiesHelper
  def us_states
    [ ['Select State','Select State'],
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end
end

app/helpers/user/reservations_helper.rb
module User::ReservationsHelper
end

app/views/user/properties/index.html.erb
<%= render partial: "shared/user_dashboard_header" %>
<% if current_user.properties.count >= 1 %>
<div class="container">
      <% @properties.each_with_index do |property, i| %>
      <hr>
      <div class="row">
        <% property.images.each do |image| %>
        <div class="col-sm-3">
          <%= image_tag(image.image.url(:index)) %>
        </div>
        <% end %>
      </div>
      <div class="row" id="edit-property-<%= property.id %>">
      <div class="form-group has success text-center form-div col-sm-6">
        <%= form_for [:user, property], url: user_property_path(current_user.slug, property.id) do |f| %>
        <h3>My Property's Information</h3>
        <div class="form-horizontal">
          <div class="form-group">
            <%= f.label :title, class:"sr-only"  %>
            <%= f.text_field :title, placeholder: "property title", class:"form-control form-control-success", maxlength: 65, required: true%>
          </div>
          <div class="form-group">
            <%= f.label :description, class:"sr-only"  %>
            <%= f.text_area :description, placeholder: "property description", class:"form-control text-input", required: true %>
          </div>
          <div class="form-group">
            <%= f.label :price, class:"sr-only"  %>
            <%= f.number_field :price, placeholder: "rental price per day", class:"form-control text-input", id: "#{property.id}-property-price", required: true %>
          </div>
          <div class="form-group">
            <%= f.collection_select(:property_type_id, PropertyType.all, :id, :name, {prompt:"property type"}, {id:"property-type", class:"form-control", required:true}) %>
          </div>
          <h3>My Property's Location</h3>
          <div class="form-group">
            <div class="col-sm-8" id="<%= property.id %>-property-street">
              <%= f.label :street, class:"sr-only"  %>
              <%= f.text_field :street, placeholder: "street", class:"form-control form-control-success", required: true %>
            </div>
            <div class="col-sm-4">
              <%= f.label :unit, class:"sr-only"  %>
              <%= f.text_field :unit, placeholder: "unit", class:"form-control form-control-success" %>
            </div>
          </div>
          <div class="form-group">
              <div class="col-sm-6">
                <%= f.label :city, class:"sr-only"  %>
                <%= f.text_field :city, placeholder: "city", class:"form-control form-control-success", required: true %>
              </div>
              <div class="col-sm-3">
                <%= f.select :state, options_for_select(us_states, property.state), {}, {class: "form-control", required: true } %>
                <%= f.label :zip, class:"sr-only"  %>
              </div>
              <div class="col-sm-3">
                <%= f.text_field :zip, placeholder: "zip", class:"form-control form-control-success", required: true %>
            </div>
          </div>
        </div>
      </div>
    <div id="new-property" class="form-group has success text-center form-div col-sm-6">
        <h3>My Property's Details</h3>
        <div class="form-group">
          <div class="col-sm-4">
            <%= f.label :bedrooms %>
            <%= f.select :bedrooms, options_for_select([*1..16], property.bedrooms), {}, {class: "form-control form-control", id: "bedroom-dropdown"} %>
          </div>
          <div class="col-sm-4">
            <%= f.label :bathrooms %>
            <%= f.select "bathrooms", options_for_select([*1..10], property.bathrooms), {}, {class: "form-control form-control",  required: true} %>
          </div>
          <div class="col-sm-4">
            <%= f.label :sleeps %>
            <%= f.select "sleeps", options_for_select([*1..25], property.sleeps), {}, {required: true, class: "form-control form-control"} %>
          </div>
        </div>
        <br><br><br>

        <h3>My Property's Amenities</h3>
        <% Amenity.all.each do |amenity| %>
          <%= check_box_tag "property[amenity_ids][]", amenity.id, property.amenities.include?(Amenity.find(amenity.id)) %>
          <%= label_tag amenity.name %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <% end %>

        <br><br>
        <h5>Upload up to 4 images less than 2mb</h5>
        <%= f.label :images, class:"sr-only"  %>
        <%= f.file_field :images, {multiple: true, id:"file_input#{i}", class:"form-control text-input", style:"display:none", accept: 'image/png,image/gif,image/jpeg' } %>
        <div class="form-inline">
          <div class="form-group">
            <label class="file">
            <input id="imageFormCover<%= i %>" class="form-control" type="text" readonly>
            <a class="btn btn-primary" onclick="$('input[id=file_input<%= i %>]').click();">change images</a>
            </label>
            <script type="text/javascript">
              $('input[id=file_input]'+ i).change(function(i) {
              $('#imageFormCover' + i).val($(this).val());
              });
            </script>
          </div>
        </div>
        <br><br>
        <div id="update-property">
          <%= f.submit "Update my Pad!", class:"btn btn-checkout" %>
        </div>
      </div>
    </div>
      <% end %>
    <% end %>
</div>
<% else %>
<%= render partial: "shared/no_listings" %>
<% end %>

app/views/user/properties/show.html.erb
<div class="property-show-hero-unit">
  <div class="container text-center hero-container">
  </div>
</div>
<div class="container">
      <div class="row">
        <h2><%= @property.title %></h2>

      <div class="col-sm-6 text-center">
        <br>
        <%= image_tag(@property.images.first.image.url(:show))%>
        <br><br>
        <div class="row">
          <div class="col-sm-3">
            <span class="glyphicon glyphicon-home show-icon" aria-hidden="true"></span>
          </div>
          <div class="col-sm-3">
            <span class="glyphicon glyphicon-bed show-icon" aria-hidden="true"></span>
          </div>
          <div class="col-sm-3">
            <span class="glyphicon glyphicon-tint show-icon" aria-hidden="true"></span>
          </div>
          <div class="col-sm-3">
            <span class="glyphicon glyphicon-user show-icon" aria-hidden="true"></span>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-3">
          <h5 class="property-stat-description"><%= @property.property_type.name %></h5  >
          </div>
          <div class="col-sm-3">
          <h5 class="property-stat-description"><%= @property.bedrooms %> Bedrooms</h5 >
          </div>
          <div class="col-sm-3">
          <h5 class="property-stat-description"><%= @property.bathrooms %> Bathrooms</h5 >
          </div>
          <div class="col-sm-3  ">
          <h5 class="property-stat-description"><%= @property.sleeps %> Guests</h5 >
          </div>
        </div>
        <h5>Amenities: <% @property.amenities.each do |amenity| %>
          * <%= amenity.name %>
        <% end %></h5>
        <p>
          <%= @property.description %>
        </p>
      </div>
      <br>
      <div class="col-sm-6">
        <div class="row calendar-container">
          <div class="col-sm-6">
          <%= month_calendar do |date| %>
            <% if @property.nights_reserved.include?(date) %>
              <span class="date-booked"><%= "X" %></span>
            <% else %>
            <%= date.day %>
            <% end %>
          <% end %>
        </div>
        <div class="col-sm-5 col-sm-offset-1">
          <%= form_tag({:controller => "properties", :action => "show"}, method: :get) do %>
          <br>
          <h5>Check in/Check out: </h5>
          <div class="form-group">
            <div class="input-group">
              <input type="text" class="form-control" name="checkin" id="checkin" selected="ok" value=<%= session[:checkin] %>>
              <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></spanselect your beverage>
            </div>
            <div class="input-group">
              <input type="text" class="form-control" name="checkout" id="checkout" value=<%= session[:checkout] %>>
              <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
            </div>
          </div>
          <input type="submit" value="Check Dates" class="btn btn-checkout btn-sm pull-right">
          <% end %>
        </div>
      </div>
        <div class="row">
        <hr>
          <div class="col-xs-4">
            <h2>Loctation:</h2>
          </div>
          <div class="col-xs-8 location-info">
            <%= @property.street %><br>
            <% if @property.unit %>
            <%= @property.unit %><br>
            <% end %>
            <%= @property.city %>, <%= @property.state %>  <%= @property.zip %>
          </div>
        </div>
          <hr>
        <div class="row text-center price-container">
            <% if session[:checkin] && session[:checkout] %>
              <h3 class="location-info">$<%= @property.price %> @ <%= @property.possible_nights(session[:checkin], session[:checkout]) %> nights = $<%= @property.cost(session[:checkin], session[:checkout]) %></h3>

            <% else %>
              <h3 class="no-date-price">$<%= @property.price  %> per night</h3>
            <% end %>
            <hr>
        </div>
        <div class="row">
            <% if current_user && session[:checkin] != nil && session[:checkout] %>
            <%= render partial: "shared/checkout_form", locals: {amount: @property.cost(session[:checkin], session[:checkout]) } %>
            <% elsif current_user %>
              <h3 class="no-date-price">Select some dates silly!</h3>
            <% else %>
            <br>
            <div class="col-sm-4 col-sm-offset-4">
              <%= link_to "Login & Book Now!", login_path, method: :get, class:"btn btn-info btn-md" %>
            </div>
            <% end %>
        </div>
      </div>
    </div>
      <hr>
    </div>
</div>
<div class="container">
  <% @property.images.each do |image| %>
  <div class="col-sm-3">
    <%= image_tag(image.image.url(:index), class:"admin-product-image") %>
  </div>
  <% end %><br>
</div>

<hr>